export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { query = '' } = req.body || {};
        const parsed = parseBudgetQuery(query);
        const plan = buildBudgetPlan(parsed);

        return res.status(200).json({
            success: true,
            plan
        });
    } catch (error) {
        console.error('budget plan api error:', error);
        return res.status(500).json({ success: false, error: 'Internal server error' });
    }
}

function parseBudgetQuery(text) {
    const query = String(text || '');

    const budgetMatch = query.match(/(?:under|within|budget\s*(?:of)?|for)\s*\$?\s*(\d+[\d,]*)\s*(usd|inr|eur|gbp)?/i)
        || query.match(/\$\s*(\d+[\d,]*)/i)
        || query.match(/(\d+[\d,]*)\s*(usd|inr|eur|gbp)\b/i);

    const daysMatch = query.match(/(\d+)\s*(?:day|days|night|nights)/i);

    const destinationMatch = query.match(/\b(?:to|in)\s+([a-zA-Z][a-zA-Z\s,.-]{1,60})\b/i);

    const budget = budgetMatch ? Number(String(budgetMatch[1]).replace(/,/g, '')) : 1200;
    const currency = normalizeCurrency((budgetMatch && budgetMatch[2]) || 'USD');
    const days = daysMatch ? Math.max(1, Number(daysMatch[1])) : 3;
    const destination = destinationMatch ? destinationMatch[1].trim() : 'your destination';

    return { budget, currency, days, destination };
}

function normalizeCurrency(input) {
    const c = String(input || 'USD').toUpperCase();
    if (['USD', 'INR', 'EUR', 'GBP'].includes(c)) return c;
    return 'USD';
}

function buildBudgetPlan({ budget, currency, days, destination }) {
    const weights = {
        lodging: 0.4,
        food: 0.25,
        transport: 0.15,
        activities: 0.15,
        buffer: 0.05
    };

    const breakdown = {
        lodging: roundMoney(budget * weights.lodging),
        food: roundMoney(budget * weights.food),
        transport: roundMoney(budget * weights.transport),
        activities: roundMoney(budget * weights.activities),
        buffer: roundMoney(budget * weights.buffer)
    };

    const dailyBudget = roundMoney(budget / days);

    const tip = `Aim for stays around ${currency} ${roundMoney(breakdown.lodging / days)} per night and keep at least ${currency} ${breakdown.buffer} as emergency buffer.`;

    return {
        destination,
        days,
        currency,
        totalBudget: roundMoney(budget),
        breakdown,
        dailyBudget,
        createdAt: new Date().toISOString(),
        title: `${days}-day budget trip to ${destination}`,
        notes: 'Generated by Unify Budget Trip Planner',
        tip
    };
}

function roundMoney(value) {
    return Math.round(Number(value) || 0);
}
