export const config = { maxDuration: 60 };
import { applyApiSecurity } from './security.js';

export default async function handler(req, res) {
    try {
        const guard = applyApiSecurity(req, res, {
            methods: ['POST'],
            routeKey: 'market-intel',
            maxBodyBytes: 64 * 1024,
            rateLimit: { max: 50, windowMs: 60 * 1000 }
        });
        if (guard.handled) return;

        const mode = resolveMode(req.body);
        if (mode === 'news' || mode === 'exchange' || mode === 'markets') {
            return res.status(410).json({
                success: false,
                error: 'Live news, finance, and market lookup have been retired in this focused build.'
            });
        }
        if (mode === 'budget_plan') {
            return await handleBudgetPlanLookup(req, res);
        }
        return res.status(410).json({
            success: false,
            error: 'Live market lookup has been retired in this focused build.'
        });
    } catch (error) {
        return res.status(200).json({
            success: false,
            error: 'market intelligence lookup failed',
            errorDetail: req?.body?.debug ? String(error?.message || error || '').slice(0, 300) : undefined
        });
    }
}

function resolveMode(body) {
    const mode = String(body?.mode || body?.service || body?.type || '').trim().toLowerCase();
    if (
        mode === 'news' ||
        mode === 'exchange' ||
        mode === 'budget_plan' ||
        mode === 'markets' ||
        mode === 'market'
    ) {
        return mode === 'market' ? 'markets' : mode;
    }

    const hasExchangeShape = Boolean(body?.from || body?.to || body?.amount || body?.date);
    if (hasExchangeShape) return 'exchange';

    const hasBudgetShape = typeof body?.query === 'string' &&
        /\b(budget|trip|travel|itinerary|under|within|days?)\b/i.test(String(body.query || ''));
    if (hasBudgetShape) return 'budget_plan';

    const hasNewsShape = Boolean(body?.category || body?.city || body?.countryCode);
    if (hasNewsShape) return 'news';

    return 'markets';
}

async function handleBudgetPlanLookup(req, res) {
    const query = String(req.body?.query || '');
    if (query.length > 1000) {
        return res.status(413).json({ success: false, error: 'query is too long' });
    }

    const parsed = parseBudgetQuery(query);
    const plan = buildBudgetPlan(parsed);
    return res.status(200).json({ success: true, plan });
}

function parseBudgetQuery(text) {
    const query = String(text || '');

    const budgetMatch = query.match(/(?:under|within|budget\s*(?:of)?|for)\s*\$?\s*(\d+[\d,]*)\s*(usd|inr|eur|gbp)?/i)
        || query.match(/\$\s*(\d+[\d,]*)/i)
        || query.match(/(\d+[\d,]*)\s*(usd|inr|eur|gbp)\b/i);

    const daysMatch = query.match(/(\d+)\s*(?:day|days|night|nights)/i);
    const destinationMatch = query.match(/\b(?:to|in)\s+([a-zA-Z][a-zA-Z\s,.-]{1,60})\b/i);

    const budget = budgetMatch ? Number(String(budgetMatch[1]).replace(/,/g, '')) : 1200;
    const currency = normalizeBudgetCurrency((budgetMatch && budgetMatch[2]) || 'USD');
    const days = daysMatch ? Math.max(1, Number(daysMatch[1])) : 3;
    const destination = destinationMatch ? destinationMatch[1].trim() : 'your destination';

    return { budget, currency, days, destination };
}

function normalizeBudgetCurrency(input) {
    const c = String(input || 'USD').toUpperCase();
    if (['USD', 'INR', 'EUR', 'GBP'].includes(c)) return c;
    return 'USD';
}

function buildBudgetPlan({ budget, currency, days, destination }) {
    const weights = {
        lodging: 0.4,
        food: 0.25,
        transport: 0.15,
        activities: 0.15,
        buffer: 0.05
    };

    const breakdown = {
        lodging: roundMoney(budget * weights.lodging),
        food: roundMoney(budget * weights.food),
        transport: roundMoney(budget * weights.transport),
        activities: roundMoney(budget * weights.activities),
        buffer: roundMoney(budget * weights.buffer)
    };

    const dailyBudget = roundMoney(budget / days);
    const tip = `Aim for stays around ${currency} ${roundMoney(breakdown.lodging / days)} per night and keep at least ${currency} ${breakdown.buffer} as emergency buffer.`;

    return {
        destination,
        days,
        currency,
        totalBudget: roundMoney(budget),
        breakdown,
        dailyBudget,
        createdAt: new Date().toISOString(),
        title: `${days}-day budget trip to ${destination}`,
        notes: 'Generated by Unify Budget Trip Planner',
        tip
    };
}

function roundMoney(value) {
    return Math.round(Number(value) || 0);
}

async function handleMarketLookup(req, res) {
    const query = String(req.body?.query || '').trim();
    if (!query) {
        return res.status(400).json({ success: false, error: 'query is required' });
    }
    if (query.length > 400) {
        return res.status(413).json({ success: false, error: 'query is too long' });
    }

    const hintedType = String(req.body?.assetType || '').trim().toLowerCase();
    const inferredType = hintedType || inferAssetType(query);

    if (inferredType === 'crypto') {
        const crypto = await lookupCrypto(query);
        return res.status(200).json(crypto);
    }
    if (inferredType === 'commodity') {
        const commodity = await lookupCommodity(query);
        return res.status(200).json(commodity);
    }

    const stock = await lookupStock(query);
    return res.status(200).json(stock);
}

function inferAssetType(query) {
    const t = String(query || '').toLowerCase();
    if (/\b(bitcoin|btc|ethereum|eth|solana|sol|dogecoin|doge|crypto|coin|token)\b/.test(t)) {
        return 'crypto';
    }
    if (/\b(gold|silver|platinum|diamond|palladium|petrol|diesel|gasoline|crude|brent|wti|commodity|fuel)\b/.test(t)) {
        return 'commodity';
    }
    return 'stock';
}

async function lookupCrypto(query) {
    const searchResponse = await fetch(`https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(query)}`);
    if (!searchResponse.ok) {
        return { success: false, error: 'crypto provider unavailable' };
    }
    const searchData = await searchResponse.json();
    const coin = Array.isArray(searchData?.coins) ? searchData.coins[0] : null;
    if (!coin?.id) {
        return { success: false, error: 'crypto asset not found' };
    }

    const priceResponse = await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent(coin.id)}&vs_currencies=usd&include_24hr_change=true&include_last_updated_at=true`);
    if (!priceResponse.ok) {
        return { success: false, error: 'crypto price unavailable' };
    }
    const priceData = await priceResponse.json();
    const coinData = priceData?.[coin.id] || {};

    const verified = await runVerifiedWebSearch([
        `${coin.name} price today`,
        `${coin.symbol} crypto price coindesk cointelegraph`,
        `${coin.name} market update latest`
    ], {
        maxResultsPerQuery: 4,
        limit: 8
    });

    return {
        success: true,
        verified: true,
        provider: 'coingecko',
        assetType: 'crypto',
        symbol: String(coin.symbol || '').toUpperCase(),
        name: coin.name,
        priceUsd: Number(coinData.usd),
        change24h: Number(coinData.usd_24h_change),
        lastUpdatedAt: coinData.last_updated_at || null,
        sourceCount: verified.results.length,
        distinctDomainCount: verified.distinctDomains.length,
        sources: verified.results.slice(0, 5).map(item => ({
            title: item.title,
            url: item.url,
            description: item.description
        }))
    };
}

async function lookupStock(query) {
    const symbol = inferTicker(query);
    const afterMarkets = await lookupStockViaAfterMarkets(query, symbol);
    if (afterMarkets) {
        return afterMarkets;
    }

    const alphaKey = process.env.ALPHA_VANTAGE_API_KEY;

    if (alphaKey && symbol) {
        const response = await fetch(`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${encodeURIComponent(symbol)}&apikey=${alphaKey}`);
        if (response.ok) {
            const data = await response.json();
            const quote = data?.['Global Quote'];
            const price = Number(quote?.['05. price']);
            if (Number.isFinite(price)) {
                const verified = await runVerifiedWebSearch([
                    `${symbol} stock price today`,
                    `${symbol} Reuters MarketWatch price`,
                    `${symbol} market update latest`
                ], {
                    maxResultsPerQuery: 4,
                    limit: 8
                });

                return {
                    success: true,
                    verified: true,
                    provider: 'alpha-vantage',
                    assetType: 'stock',
                    symbol,
                    price,
                    change: Number(quote?.['09. change']),
                    changePercent: quote?.['10. change percent'] || '',
                    tradingDay: quote?.['07. latest trading day'] || null,
                    sourceCount: verified.results.length,
                    distinctDomainCount: verified.distinctDomains.length,
                    sources: verified.results.slice(0, 5).map(item => ({
                        title: item.title,
                        url: item.url,
                        description: item.description
                    }))
                };
            }
        }
    }

    const verified = await runVerifiedWebSearch([
        `${query} stock price today`,
        `${query} market update Reuters Bloomberg CNBC`,
        `${query} latest stock news`
    ], {
        maxResultsPerQuery: 5,
        limit: 10
    });

    return {
        success: verified.results.length > 0,
        verified: verified.results.length > 0,
        provider: alphaKey ? 'web-fallback' : 'web-fallback-no-stock-api-key',
        assetType: 'stock',
        symbol: symbol || '',
        sourceCount: verified.results.length,
        distinctDomainCount: verified.distinctDomains.length,
        sources: verified.results.slice(0, 6).map(item => ({
            title: item.title,
            url: item.url,
            description: item.description
        }))
    };
}

async function lookupStockViaAfterMarkets(query, symbolHint) {
    const baseUrl = String(process.env.AFTERMARKETS_API_BASE || 'https://api.aftermarkets.in').replace(/\/+$/, '');
    const token = process.env.AFTERMARKETS_API_KEY || process.env.AFTERMARKETS_TOKEN || '';
    const symbol = normalizeAfterMarketsSymbol(symbolHint || inferTicker(query) || String(query || '').trim());
    if (!symbol) return null;

    const headers = token
        ? { Authorization: `Bearer ${token}` }
        : {};
    const candidates = [
        `${baseUrl}/api/v1/stocks/quote?symbol=${encodeURIComponent(symbol)}`,
        `${baseUrl}/v1/stocks/quote?symbol=${encodeURIComponent(symbol)}`,
        `${baseUrl}/api/stocks/quote?symbol=${encodeURIComponent(symbol)}`,
        `${baseUrl}/stocks/quote?symbol=${encodeURIComponent(symbol)}`,
        `${baseUrl}/quote?symbol=${encodeURIComponent(symbol)}`
    ];

    for (const url of candidates) {
        try {
            const response = await fetch(url, { headers });
            if (!response.ok) continue;
            const data = await response.json();
            const parsed = parseAfterMarketsQuote(data, symbol);
            if (!parsed) continue;

            const verified = await runVerifiedWebSearch([
                `${parsed.symbol} stock price today`,
                `${parsed.symbol} market update Reuters Bloomberg CNBC`,
                `${parsed.name || parsed.symbol} latest stock news`
            ], {
                maxResultsPerQuery: 4,
                limit: 8
            });

            return {
                success: true,
                verified: true,
                provider: 'aftermarkets.in',
                assetType: 'stock',
                symbol: parsed.symbol,
                name: parsed.name || '',
                price: parsed.price,
                change: parsed.change,
                changePercent: parsed.changePercent,
                tradingDay: parsed.tradingDay,
                sourceCount: verified.results.length,
                distinctDomainCount: verified.distinctDomains.length,
                sources: verified.results.slice(0, 5).map(item => ({
                    title: item.title,
                    url: item.url,
                    description: item.description
                }))
            };
        } catch (_) {}
    }

    return null;
}

function normalizeAfterMarketsSymbol(raw) {
    const text = String(raw || '').toUpperCase().replace(/\s+/g, '').trim();
    if (!text) return '';
    if (text.includes(':')) return text;
    if (/^[A-Z]{1,10}$/.test(text)) return `NSE:${text}`;
    return text;
}

function parseAfterMarketsQuote(payload, symbolFallback) {
    const node = payload?.data || payload?.result || payload?.quote || payload;
    if (!node || typeof node !== 'object') return null;

    const pick = (...keys) => {
        for (const key of keys) {
            if (node[key] !== undefined && node[key] !== null && node[key] !== '') {
                return node[key];
            }
        }
        return null;
    };

    const price = Number(pick('lastPrice', 'ltp', 'price', 'close', 'value'));
    if (!Number.isFinite(price)) return null;

    const symbol = String(pick('symbol', 'ticker', 'tradingsymbol', 'code') || symbolFallback || '').toUpperCase();
    const change = toFiniteNumber(pick('change', 'netChange', 'priceChange'));
    const changePercentRaw = pick('pChange', 'changePercent', 'percentChange');
    const changePercent = changePercentRaw === null || changePercentRaw === undefined
        ? ''
        : String(changePercentRaw).replace(/\s+/g, '').endsWith('%')
            ? String(changePercentRaw)
            : `${changePercentRaw}%`;
    const tradingDay = String(pick('lastUpdated', 'timestamp', 'updatedAt', 'tradingDay', 'date') || '') || null;
    const name = String(pick('name', 'companyName', 'displayName') || '').trim();

    return { symbol, name, price, change, changePercent, tradingDay };
}

function toFiniteNumber(value) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
}

function inferTicker(query) {
    const upper = String(query || '').toUpperCase().trim();
    const match = upper.match(/\b[A-Z]{1,5}\b/);
    return match ? match[0] : '';
}

async function lookupCommodity(query) {
    const profile = inferCommodityProfile(query);
    const verified = await runVerifiedWebSearch(buildCommodityQueries(query, profile), {
        maxResultsPerQuery: 5,
        limit: 10
    });
    const extracted = extractPriceFromResults(verified.results, profile);

    return {
        success: verified.results.length > 0,
        verified: verified.results.length > 0,
        provider: 'web-verified-commodity',
        assetType: 'commodity',
        commodityType: profile.kind,
        symbol: profile.token.toUpperCase(),
        name: profile.label,
        unit: profile.unit,
        price: extracted.price,
        currency: extracted.currency,
        sourceCount: verified.results.length,
        distinctDomainCount: verified.distinctDomains.length,
        sources: verified.results.slice(0, 6).map(item => ({
            title: item.title,
            url: item.url,
            description: item.description
        }))
    };
}

function inferCommodityProfile(query) {
    const t = String(query || '').toLowerCase();
    if (/\bpetrol|gasoline\b/.test(t)) {
        return { kind: 'fuel', label: 'Petrol', token: 'petrol', unit: 'per litre' };
    }
    if (/\bdiesel\b/.test(t)) {
        return { kind: 'fuel', label: 'Diesel', token: 'diesel', unit: 'per litre' };
    }
    if (/\bgold\b/.test(t)) {
        return { kind: 'metal', label: 'Gold', token: 'gold', unit: 'per ounce' };
    }
    if (/\bsilver\b/.test(t)) {
        return { kind: 'metal', label: 'Silver', token: 'silver', unit: 'per ounce' };
    }
    if (/\bplatinum\b/.test(t)) {
        return { kind: 'metal', label: 'Platinum', token: 'platinum', unit: 'per ounce' };
    }
    if (/\bdiamond\b/.test(t)) {
        return { kind: 'gem', label: 'Diamond', token: 'diamond', unit: 'market quote' };
    }
    return { kind: 'commodity', label: 'Commodity', token: 'commodity', unit: 'market quote' };
}

function buildCommodityQueries(rawQuery, profile) {
    const q = String(rawQuery || '').trim();
    if (profile.kind === 'fuel') {
        return [
            `${profile.token} price today India`,
            `${profile.token} price today IOCL HPCL BPCL`,
            `${profile.token} price per litre Bloomberg Reuters`,
            q
        ];
    }
    if (profile.kind === 'metal' || profile.kind === 'gem') {
        return [
            `${profile.token} price today`,
            `${profile.token} spot price Bloomberg Reuters`,
            `${profile.token} price today kitco investing.com`,
            q
        ];
    }
    return [
        `${q} latest price today`,
        `${q} price Bloomberg Reuters`,
        q
    ];
}

function extractPriceFromResults(results, profile) {
    const pool = Array.isArray(results) ? results : [];
    for (const item of pool.slice(0, 8)) {
        const haystack = `${item?.title || ''} ${item?.description || ''}`;
        const parsed = extractPriceCandidate(haystack, profile);
        if (parsed) return parsed;
    }
    return { price: null, currency: '' };
}

function extractPriceCandidate(text, profile) {
    const body = String(text || '').replace(/\s+/g, ' ').trim();
    if (!body) return null;

    const inrMatch = body.match(/(?:\u20B9|rs\.?|inr)\s*([0-9]{1,3}(?:,[0-9]{2,3})*(?:\.[0-9]+)?)/i);
    if (inrMatch?.[1]) {
        const value = parseNumber(inrMatch[1]);
        if (isPlausiblePrice(value, profile)) return { price: value, currency: 'INR' };
    }

    const usdMatch = body.match(/(?:usd|us\$|\$)\s*([0-9]{1,5}(?:,[0-9]{3})*(?:\.[0-9]+)?)/i);
    if (usdMatch?.[1]) {
        const value = parseNumber(usdMatch[1]);
        if (isPlausiblePrice(value, profile)) return { price: value, currency: 'USD' };
    }

    return null;
}

function parseNumber(raw) {
    const value = Number(String(raw || '').replace(/,/g, ''));
    return Number.isFinite(value) ? value : null;
}

function isPlausiblePrice(value, profile) {
    if (!Number.isFinite(value) || value <= 0) return false;
    if (profile.kind === 'fuel') return value >= 10 && value <= 1000;
    if (profile.kind === 'metal') return value >= 1 && value <= 100000;
    if (profile.kind === 'gem') return value >= 1 && value <= 1000000;
    return value >= 1 && value <= 1000000;
}

async function handleExchangeLookup(req, res) {
    const from = String(req.body?.from || '').trim().toUpperCase();
    const to = String(req.body?.to || '').trim().toUpperCase();
    const amount = Number(req.body?.amount ?? 1);
    const date = String(req.body?.date || '').trim();

    if (!/^[A-Z]{3}$/.test(from) || !/^[A-Z]{3}$/.test(to)) {
        return res.status(400).json({ error: 'Valid 3-letter currency codes are required.' });
    }
    if (!Number.isFinite(amount) || amount <= 0 || amount > 1e9) {
        return res.status(400).json({ error: 'Amount must be a positive number.' });
    }
    if (date && !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        return res.status(400).json({ error: 'date must be in YYYY-MM-DD format.' });
    }

    try {
        const endpoint = date
            ? `https://api.frankfurter.dev/v1/${encodeURIComponent(date)}?base=${from}&symbols=${to}`
            : `https://api.frankfurter.dev/v1/latest?base=${from}&symbols=${to}`;
        const response = await fetch(endpoint);
        if (!response.ok) {
            return res.status(502).json({ error: 'Exchange provider unavailable.' });
        }
        const data = await response.json();
        const rate = Number(data?.rates?.[to]);
        if (!Number.isFinite(rate)) {
            return res.status(502).json({ error: 'Exchange rate unavailable.' });
        }

        let verified = {
            results: [],
            distinctDomains: [],
            trustedCount: 0
        };
        try {
            verified = await runVerifiedWebSearch([
                `${from} ${to} exchange rate today`,
                `${from} to ${to} rate xe oanda x-rates`,
                `${from} ${to} exchange rate Reuters OR ECB`
            ], {
                maxResultsPerQuery: 4,
                limit: 8
            });
        } catch (_) {}

        const providerSource = {
            title: `Frankfurter exchange rates ${from}/${to}`,
            url: endpoint,
            description: `Live exchange-rate API response dated ${data?.date || date || 'latest'}.`
        };
        const sourceResults = [providerSource, ...((verified.results || []).slice(0, 4).map(item => ({
            title: item.title,
            url: item.url,
            description: item.description
        })))];
        const distinctDomains = Array.from(new Set(sourceResults.map(item => {
            try {
                return new URL(item.url).hostname.toLowerCase().replace(/^www\./, '');
            } catch (_) {
                return '';
            }
        }).filter(Boolean)));

        return res.status(200).json({
            success: true,
            verified: true,
            provider: 'frankfurter',
            date: data?.date || date || null,
            from,
            to,
            amount,
            rate,
            convertedAmount: amount * rate,
            sourceCount: sourceResults.length,
            distinctDomainCount: distinctDomains.length,
            trustedCount: verified.trustedCount || 0,
            sources: sourceResults
        });
    } catch (error) {
        return res.status(200).json({
            success: false,
            error: 'exchange lookup failed',
            errorDetail: req?.body?.debug ? String(error?.message || error || '').slice(0, 300) : undefined
        });
    }
}

async function handleNewsLookup(req, res) {
    const query = String(req.body?.query || '').trim();
    const category = String(req.body?.category || '').trim();
    const city = String(req.body?.city || '').trim();
    const countryCode = String(req.body?.countryCode || '').trim();
    const verificationMode = normalizeNewsVerificationMode(
        req.body?.verificationMode || req.body?.newsVerificationMode || 'normal'
    );
    const riskLevel = normalizeRiskLevel(req.body?.riskLevel || req.body?.verificationRiskLevel || 'high_risk');
    if ([query, category, city, countryCode].some(value => value.length > 500)) {
        return res.status(413).json({
            success: false,
            error: 'news query is too long',
            verificationMode,
            riskLevel,
            sourceCount: 0,
            distinctDomainCount: 0,
            trustedCount: 0,
            verified: false,
            articles: []
        });
    }

    const topic = normalizeTopic(query || category || (city ? `${city} news` : 'latest news'));
    const queries = [
        topic,
        `latest ${topic}`,
        `${topic} Reuters OR AP OR BBC OR Al Jazeera`
    ];
    if (!query && city) queries.push(`${city} breaking news`);
    if (!query && countryCode && countryCode !== 'DEFAULT') queries.push(`${countryCode} national news`);

    try {
        const settled = await Promise.allSettled([
            runVerifiedWebSearch(queries, {
                maxResultsPerQuery: 6,
                limit: 10
            }),
            fetchGoogleNewsRss(topic)
        ]);

        const verified = settled[0]?.status === 'fulfilled'
            ? settled[0].value
            : { results: [], distinctDomains: [], trustedCount: 0 };
        const rssArticles = settled[1]?.status === 'fulfilled'
            ? settled[1].value
            : [];

        if (rssArticles.length) {
            const rssMeta = computeNewsSourceMeta(rssArticles, verificationMode, riskLevel);
            if (rssMeta.strongEnough) {
                return res.status(200).json({
                    success: true,
                    verified: true,
                    verificationMode,
                    riskLevel,
                    query: topic,
                    sourceCount: rssMeta.sourceCount,
                    distinctDomainCount: rssMeta.distinctDomainCount,
                    trustedCount: rssMeta.trustedCount,
                    articles: rssArticles
                });
            }
        }

        const verifiedArticles = verified.results.map(item => ({
            title: item.title,
            url: item.url,
            description: item.description
        }));
        const verifiedMeta = computeNewsSourceMeta(verifiedArticles, verificationMode, riskLevel);
        if (verifiedMeta.strongEnough) {
            return res.status(200).json({
                success: true,
                verified: true,
                verificationMode,
                riskLevel,
                query: topic,
                sourceCount: verifiedMeta.sourceCount,
                distinctDomainCount: verifiedMeta.distinctDomainCount,
                trustedCount: verifiedMeta.trustedCount,
                articles: verifiedArticles
            });
        }

        if (!verifiedArticles.length) {
            return res.status(200).json({
                success: true,
                verified: false,
                verificationMode,
                riskLevel,
                query: topic,
                sourceCount: 0,
                distinctDomainCount: 0,
                trustedCount: 0,
                articles: []
            });
        }

        return res.status(200).json({
            success: true,
            verified: false,
            verificationMode,
            riskLevel,
            query: topic,
            sourceCount: verifiedMeta.sourceCount,
            distinctDomainCount: verifiedMeta.distinctDomainCount,
            trustedCount: verifiedMeta.trustedCount,
            articles: []
        });
    } catch (error) {
        return res.status(200).json({
            success: false,
            error: 'news lookup failed',
            verificationMode,
            riskLevel,
            sourceCount: 0,
            distinctDomainCount: 0,
            trustedCount: 0,
            verified: false,
            query: String(req.body?.query || req.body?.category || '').trim(),
            articles: []
        });
    }
}

function normalizeTopic(text) {
    const raw = String(text || '').trim();
    if (!raw) return '';
    return extractSearchTopic(raw) || raw;
}

async function fetchGoogleNewsRss(topic) {
    const url = `https://news.google.com/rss/search?q=${encodeURIComponent(topic)}&hl=en-US&gl=US&ceid=US:en`;
    const response = await fetch(url, {
        headers: {
            Accept: 'application/rss+xml, application/xml, text/xml'
        }
    });
    if (!response.ok) return [];

    const xml = await response.text();
    const items = [];
    const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
    let match;
    while ((match = itemRegex.exec(xml)) && items.length < 8) {
        const block = match[1];
        const title = decodeXml(getTag(block, 'title'));
        const link = decodeXml(getTag(block, 'link'));
        const description = decodeXml(stripHtml(getTag(block, 'description')));
        const source = parseGoogleNewsSource(block);
        const sourceUrl = normalizeSourceUrl(source?.url || '');
        if (!title || !link) continue;
        items.push({
            title: cleanGoogleNewsTitle(title),
            url: sourceUrl || link,
            description: description || title,
            sourceName: source?.name || ''
        });
    }
    return items;
}

function getTag(block, tag) {
    const regex = new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`, 'i');
    return regex.exec(block)?.[1] || '';
}

function stripHtml(input) {
    return String(input || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
}

function decodeXml(input) {
    return String(input || '')
        .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/\s+/g, ' ')
        .trim();
}

function cleanGoogleNewsTitle(title) {
    return String(title || '').replace(/\s+-\s+[^-]+$/, '').trim();
}

function parseGoogleNewsSource(itemBlock) {
    const sourceTag = String(itemBlock || '').match(/<source\b([^>]*)>([\s\S]*?)<\/source>/i);
    if (!sourceTag) return null;
    const attrs = sourceTag[1] || '';
    const name = decodeXml(sourceTag[2] || '');
    const urlMatch = attrs.match(/\burl=(["'])(.*?)\1/i);
    return {
        name,
        url: decodeXml(urlMatch?.[2] || '')
    };
}

function normalizeSourceUrl(url) {
    const value = String(url || '').trim();
    if (!value) return '';
    if (!/^https?:\/\//i.test(value)) return '';
    return value;
}

function computeNewsSourceMeta(articles, verificationMode = 'normal', riskLevel = 'high_risk') {
    const rows = Array.isArray(articles) ? articles.filter(Boolean) : [];
    const domains = new Set();
    let trustedCount = 0;

    for (const article of rows) {
        const url = String(article?.url || '').trim();
        const domain = getDomainFromUrl(url);
        if (domain) domains.add(domain);
        if (isTrustedLiveSource(url)) trustedCount++;
    }

    const sourceCount = rows.length;
    const distinctDomainCount = domains.size;
    const threshold = getNewsVerificationThreshold(verificationMode, riskLevel);
    const strongEnough =
        sourceCount >= threshold.minArticles &&
        distinctDomainCount >= threshold.minDomains &&
        trustedCount >= threshold.minTrusted;

    return {
        sourceCount,
        distinctDomainCount,
        trustedCount,
        strongEnough
    };
}

function normalizeNewsVerificationMode(value) {
    const mode = String(value || '').trim().toLowerCase();
    return mode === 'strict' ? 'strict' : 'normal';
}

function normalizeRiskLevel(value) {
    const level = String(value || '').trim().toLowerCase();
    if (level === 'medium_risk' || level === 'low_risk') return level;
    return 'high_risk';
}

function getNewsVerificationThreshold(mode, riskLevel = 'high_risk') {
    if (riskLevel === 'medium_risk') {
        return {
            minArticles: 2,
            minDomains: 2,
            minTrusted: 1
        };
    }
    if (riskLevel === 'low_risk') {
        return {
            minArticles: 1,
            minDomains: 1,
            minTrusted: 0
        };
    }
    if (mode === 'strict') {
        return {
            minArticles: 3,
            minDomains: 2,
            minTrusted: 2
        };
    }
    return {
        minArticles: 2,
        minDomains: 2,
        minTrusted: 1
    };
}


